---
title: "Fitting models to time series data Sierra2017"
author: "Mina Azizi-Rad"
date: ""
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error = TRUE)
packs <- c('SoilR', 'sidb', 'R.utils', 'dplyr')
sapply(packs, require, character.only=TRUE)
rm(list=ls())

```



```{r sidb database, results='hide'}
db=loadEntries(path="~/sidb/data/")
db_flat=flatterSIDb(db)
```

```{r}
plotEntry(db[[24]])
```


```{r }
FitModel<- function(db, ts.col, ic.col, UnitConverter,
                          inipars= list(c(0.01, 0.001, 0.1),
                                        c(5e-03, 1e-05, 0.1, 0.01, 0.01), 
                                        c(5e-03, 1e-05, 0.1, 0.01))){
  mod0 <- onepFitFlux(timeSeries = db$timeSeries[, c(1,ts.col)], initialCarbon = db$initConditions[ic.col, 'carbonMean']*UnitConverter)
  mod1 <- twoppFit(timeSeries = db$timeSeries[, c(1,ts.col)], initialCarbon = db$initConditions[ic.col, 'carbonMean']*UnitConverter, 
                     inipars = inipars[[1]])
  mod2 <- twopfFit(timeSeries = db$timeSeries[, c(1,ts.col)], initialCarbon = db$initConditions[ic.col, 'carbonMean']*UnitConverter, 
                   inipars = inipars[[2]])
  mod3 <- twopsFit(timeSeries = db$timeSeries[, c(1,ts.col)], initialCarbon = db$initConditions[ic.col, 'carbonMean']*UnitConverter, 
                   inipars = inipars[[3]])
  
  days= mod1$SoilRmodel@times
  Mlist=list(mod0, mod1, mod2, mod3)
  modelNames=c("One-pool","Two-pool parallel" ,"Two-pool feedback", "Two-pool series")
  Rt=lapply(Mlist, function(x){getReleaseFlux(x$SoilRmodel)})
  
  par(mfrow=c(2,2))
  for (i in c(1:4)){
    matplot(days, Rt[[i]], type="l", lty=1, ylab=db$variables$V2$units, xlab="Day", 
    main=modelNames[i])
    points(db$timeSeries[, c(1,ts.col)], pch=19, cex=0.5)}
  par(mfrow=c(1,1))
  
  #Calculating the AIC 
  AIC=sapply(Mlist, function(x){AIC=x$AIC})
  K=sapply(Mlist, function(x){length(x$FMEmodel$par)})
  n=nrow(db$timeSeries[, c(1,ts.col)])
    
  AICc=list(NULL)
  for(i in 1:length(Mlist)){
    AICc[[i]]=AIC[[i]]+( (2*K[[i]]*(K[[i]]+1))/(n-K[[i]]-1))
  }
  AICmin=min(unlist(AICc))
  
  delta_i=list(NULL)
  for(i in 1:length(AICc)){
    delta_i[[i]]=AICc[[i]]-AICmin
  }
  
  wi=list(NULL)
  for(i in 1:length(delta_i)){
    wi[[i]]=exp(-0.5 * delta_i[[i]])/(exp(-0.5* delta_i[[1]]) + exp(-0.5*delta_i[[2]]) + exp(-0.5*delta_i[[3]]) )
  }
  # Transit time based on each model
  a1=mod1$SoilRmodel@mat@map() ;gam=mod1$SoilRmodel@initialValues #vector of initial values in each pool
  tt1= transitTime(A = a1, u =gam, q = 0.5, a = 0)

  a2=mod2$SoilRmodel@mat@map()
  tt2=transitTime(A = a2, u =c(1, 0), q = 0.5, a = 0)

  a3=mod3$SoilRmodel@mat@map()
  tt3=transitTime(A = a3, u =c(1, 0), q = 0.5, a = 0)
  
  TT=c(NA, tt1$meanTransitTime, tt2$meanTransitTime, tt3$meanTransitTime)
  q05=c(NA, tt1$quantiles, tt2$quantiles, tt3$quantiles)
  
  # Model parameters to be collected in the table
  k1=sapply(Mlist, function(x){x$FMEmodel$par[1]})
  k2=sapply(Mlist, function(x){x$FMEmodel$par[2]})

  pC0= c(NA, mod1$FMEmodel$par[3], mod2$FMEmodel$par[5], mod3$FMEmodel$par[4])
  a21=c(NA, NA, mod2$FMEmodel$par[3], mod3$FMEmodel$par[3])
  a12=c(NA, NA, mod2$FMEmodel$par[4], NA)
  
  tbldb <- data.frame(model=modelNames, AIC=AIC, k1=k1, k2=k2, C0Inp1=pC0, a21=a21, a12=a12, AICc= unlist(AICc), wi=unlist(wi), MeanTrT=TT, q05=q05 )
  
  #Collect all the results in a table
  tbldb %>% dplyr::mutate_if(is.numeric, funs(as.character(signif(., 3)))) %>%
    knitr::kable(.)
}
```


# Dataset `r db[[24]]$citationKey` 

A dataset with 17 variables of `r db_flat$vars$Sierra2017BG[1,"incDesc"] `, two levels of temperature, 4 levels of soil moisture and 2 levels of oxygen as treatments

gas measurement units in mgC/day and the initial carbon has been measured as mgC/mgSoil

```{r}
FitModel(db = db[[24]], ts.col = 2, ic.col = 1, UnitConverter = 10, 
         inipars= list(c(0.05, 0.005, 0.1),
                       c(0.05, 0.00005, 0.1, 0.01, 0.01),
                       c(0.05, 0.00005, 0.1, 0.01)) )
```

```{r}
FitModel(db = db[[24]], ts.col = 3, ic.col = 1, UnitConverter = 1e3 , 
         inipars= list(c(0.05, 0.005, 0.1),
                       c(0.05, 0.00005, 0.1, 0.01, 0.01),
                       c(0.05, 0.00005, 0.1, 0.01)))
```

```{r}
FitModel(db = db[[24]], ts.col = 4, ic.col = 1, UnitConverter = 1e3 , 
         inipars= list(c(0.05, 0.005, 0.1),
                       c(0.05, 0.00005, 0.1, 0.01, 0.01),
                       c(0.05, 0.00005, 0.1, 0.01)))
```

```{r}
FitModel(db = db[[24]], ts.col = 5, ic.col = 1, UnitConverter = 1e3 , 
         inipars= list(c(0.05, 0.005, 0.1),
                       c(0.05, 0.00005, 0.1, 0.01, 0.01),
                       c(0.05, 0.00005, 0.1, 0.01)))
```

```{r}
FitModel(db = db[[24]], ts.col = 6, ic.col = 1, UnitConverter = 1e3 , 
         inipars= list(c(0.05, 0.005, 0.1),
                       c(0.05, 0.00005, 0.1, 0.01, 0.01),
                       c(0.05, 0.00005, 0.1, 0.01)))
```

```{r}
FitModel(db = db[[24]], ts.col = 7, ic.col = 1, UnitConverter = 1e3 , 
         inipars= list(c(0.05, 0.005, 0.1),
                       c(0.05, 0.00005, 0.1, 0.01, 0.01),
                       c(0.05, 0.00005, 0.1, 0.01)))
```

```{r}
FitModel(db = db[[24]], ts.col = 8, ic.col = 1, UnitConverter = 1e3 , 
         inipars= list(c(0.05, 0.005, 0.1),
                       c(0.05, 0.00005, 0.1, 0.01, 0.01),
                       c(0.05, 0.00005, 0.1, 0.01)))
```

```{r}
FitModel(db = db[[24]], ts.col = 9, ic.col = 1, UnitConverter = 1e3 , 
         inipars= list(c(0.05, 0.005, 0.1),
                       c(0.05, 0.00005, 0.1, 0.01, 0.01),
                       c(0.05, 0.00005, 0.1, 0.01)))
```

```{r}
FitModel(db = db[[24]], ts.col = 10, ic.col = 1, UnitConverter = 1e3 , 
         inipars= list(c(0.05, 0.005, 0.1),
                       c(0.05, 0.00005, 0.1, 0.01, 0.01),
                       c(0.05, 0.00005, 0.1, 0.01)))
```

```{r}
FitModel(db = db[[24]], ts.col = 11, ic.col = 1, UnitConverter = 1e3 , 
         inipars= list(c(0.05, 0.005, 0.1),
                       c(0.05, 0.00005, 0.1, 0.01, 0.01),
                       c(0.05, 0.00005, 0.1, 0.01)))
```

```{r}
FitModel(db = db[[24]], ts.col = 12, ic.col = 1, UnitConverter = 1e3 , 
         inipars= list(c(0.05, 0.005, 0.1),
                       c(0.05, 0.00005, 0.1, 0.01, 0.01),
                       c(0.05, 0.00005, 0.1, 0.01)))
```


```{r}
FitModel(db = db[[24]], ts.col = 13, ic.col = 1, UnitConverter = 1e3 , 
         inipars= list(c(0.05, 0.005, 0.1),
                       c(0.05, 0.00005, 0.1, 0.01, 0.01),
                       c(0.05, 0.00005, 0.1, 0.01)))
```

```{r}
FitModel(db = db[[24]], ts.col = 14, ic.col = 1, UnitConverter = 1e3 , 
         inipars= list(c(0.05, 0.005, 0.1),
                       c(0.05, 0.00005, 0.1, 0.01, 0.01),
                       c(0.05, 0.00005, 0.1, 0.01)))
```

```{r}
FitModel(db = db[[24]], ts.col = 15, ic.col = 1, UnitConverter = 1e3 , 
         inipars= list(c(0.05, 0.005, 0.1),
                       c(0.05, 0.00005, 0.1, 0.01, 0.01),
                       c(0.05, 0.00005, 0.1, 0.01)))
```

```{r}
FitModel(db = db[[24]], ts.col = 16, ic.col = 1, UnitConverter = 1e3 , 
         inipars= list(c(0.05, 0.005, 0.1),
                       c(0.05, 0.00005, 0.1, 0.01, 0.01),
                       c(0.05, 0.00005, 0.1, 0.01)))
```

```{r}
FitModel(db = db[[24]], ts.col = 17, ic.col = 1, UnitConverter = 1e3 , 
         inipars= list(c(0.05, 0.005, 0.1),
                       c(0.05, 0.00005, 0.1, 0.01, 0.01),
                       c(0.05, 0.00005, 0.1, 0.01)))
```
